<a href="https://colab.research.google.com/github/ryanstwrt/osu-transport/blob/gh-pages/users/stewryan/juypter_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 1: Python Introduction and Numpy
by Leslie Kerby with some material adapted from Berkeley Data Science

## 1. Jupyter notebooks
This webpage is called a Jupyter notebook. A notebook is a place to write programs and view their results.

### 1.1. Text cells
In a notebook, each rectangle containing text or code is called a *cell*.

Text cells (like this one) can be edited by double-clicking on them. They're written in a simple format called [Markdown](http://daringfireball.net/projects/markdown/syntax) to add formatting and section headings.  You don't need to learn Markdown, but you might want to.

After you edit a text cell, select the 'run cell' button at the top that looks like ▶| to confirm any changes.

### 1.2. Code cells
Code cells, like the one below, can be executed with the 'run cell' ▶| button on the top. Or you can use the keyboard shortcut `Ctrl + Enter`. Try it. Another useful keyboard shortcut is `Alt + Enter` which will execute the cell AND add a new code cell below it. If you want to delete a cell, click on it and tap the 'scissors' button.

In [0]:
print("Hello, World!")

Hello, World!


There is your first 'Hello, World!' program. Pretty simple. <br/>
`print` is a useful function and we will use it throughout the workshop. Note that you can use single quotes `'` or double quotes `"`; it does not care. Try running the next cell.

In [0]:
print('\N{WAVING HAND SIGN}, \N{EARTH GLOBE ASIA-AUSTRALIA}!')

👋, 🌏!


**Question 1.2.1.** <br />
Change the cell below so that it prints out:

    First this line,
    then the whole 🌏,
    and then this one.

In [0]:
print('First this line,')
print('and then this one.')

First this line,
and then this one.


A new cell starts out as code.  You can change it to a text cell by selecting it so that it's highlighted, then selecting the drop-down box next to the restart (⟳) button in the menu bar, and choosing Markdown instead of Code.

### 1.3. The Kernel
The kernel is a program that executes the code inside your notebook and outputs the results. In the top right of your window, you can see a circle that indicates the status of your kernel. If the circle is empty (⚪), the kernel is idle and ready to execute code. If the circle is filled in (⚫), the kernel is busy running some code. 

You may run into problems where your kernel is stuck for an excessive amount of time, your notebook is very slow and unresponsive, or your kernel loses its connection. If this happens, try the following steps:
1. At the top of your screen, select **Kernel**, then **Interrupt**.
2. If that doesn't help, select **Kernel**, then **Restart**. If you do this, you will have to run your code cells from the start of your notebook up until where you paused your work.
3. If that doesn't help, restart your server. First, save your work by selecting **File** at the top left of your screen, then **Save and Checkpoint** (or by clicking the disk icon or by pressing `Ctrl + S`). Next, select **Control Panel** at the top right. Choose **Stop My Server** to shut it down, then **My Server** to start it back up. Then, navigate back to the notebook you were working on.

## 2. Introduction to Python

### 2.1. Numbers

Quantitative information arises everywhere in data science. The expression `3.2500` evaluates to the number 3.25. (Run the cell and see.)

In [0]:
3.2500

3.25

Notice that we didn't have to `print`. When you run a notebook cell, if the last line has a value, then Jupyter helpfully prints out that value for you. However, it won't print out prior lines automatically. If you want to print out a prior line, you need to add the `print` statement. Run the cell below to check.

In [0]:
print(2)
3
4

2


4

Above, you should see that 4 is the value of the last expression, 2 is printed, but 3 is lost forever because it was neither printed nor last.

You don't want to print everything all the time anyway.  But if you feel sorry for 3, change the cell above to print it.

### 2.2. Arithmetic
Many basic arithmetic operations are built in to Python. The common operator that differs from typical math notation is `**`, which raises one number to the power of the other: `2**3` stands for $2^3$ and evaluates to 8. Typing `2^3` won't work. 

The order of operations is what you learned in elementary school, and Python also has parentheses.  For example, compare the outputs of the cells below. Use parentheses for a happy new year!

In [0]:
3+6*5-6*3**2*2**3/4*7

-723.0

In [0]:
3+(6*5-(6*3))**2*((2**3)/4*7)

2019.0

In standard math notation, the first expression is

$$3 + 6 \times 5 - 6 \times 3^2 \times \frac{2^3}{4} \times 7,$$

while the second expression is

$$3 + (6 \times 5 - (6 \times 3))^2 \times (\frac{(2^3)}{4} \times 7).$$

**Question 2.2.1.** <br /> Write a Python expression in this next cell that's equal to $5 \times (3 \frac{10}{11}) - 49 \frac{1}{3} + 2^{0.5 \times 22} + \frac{26}{33}$.  That's five times three and ten elevenths, minus 49 and a third, plus two to the power of half of 22, plus 26 33rds.  By "$3 \frac{10}{11}$" we mean $3+\frac{10}{11}$, not $3 \times \frac{10}{11}$.

Replace the ellipses (`...`) with your expression. 

*Hint:* The correct output should be a familiar number.

In [0]:
...

Ellipsis

### 2.3. Variables/Names
In Python, we do not have to specify the data type of the variable we are instantiating. It infers it from what is assigned to it. Execute the assignment statement below.

In [0]:
ten = 3 * 2 + 4

Now when we tell Python to print out the variable `ten` it will print out its value.

In [0]:
print(ten)

10


To check what type a variable is, use the `type` function.

In [0]:
type(ten)

int

A common pattern in Jupyter notebooks is to assign a value to a name and then immediately evaluate the name in the last line in the cell so that the value is displayed as output. 

In [0]:
close_to_pi = 355/113
close_to_pi

3.1415929203539825

Another common pattern is that a series of lines in a single cell will build up a complex computation in stages, naming the intermediate results.

In [0]:
bimonthly_salary = 840
monthly_salary = 2 * bimonthly_salary
number_of_months_in_a_year = 12
yearly_salary = number_of_months_in_a_year * monthly_salary
yearly_salary

Names in Python can have letters (upper- and lower-case letters are both okay and count as different letters), underscores, and numbers.  The first character can't be a number (otherwise a name might look like a number).  And names can't contain spaces, since spaces are used to separate pieces of code from each other.

Other than those rules, what you name something doesn't matter *to Python*.  For example, this cell does the same thing as the above cell, except everything has a different name:

In [0]:
a = 840
b = 2 * a
c = 12
d = c * b
d

**However**, names are very important for making your code *readable* to yourself and others.  The cell above is shorter, but it's totally useless without an explanation of what it does.

**Question 2.3.1.** <br /> Assign the name `seconds_in_a_decade` to the number of seconds between midnight January 1, 2010 and midnight January 1, 2020. Use Python to perform any required arithmetic.

In [0]:
# Change the next line so that it computes the number of
# seconds in a decade and assigns that number the name
# seconds_in_a_decade.
seconds_in_a_decade = ...

# We've put this line in this cell so that it will print
# the value you've given to seconds_in_a_decade when you
# run it.  You don't need to change this.
seconds_in_a_decade

**Comments**<br/>
Note that `#` is used to create a comment. You can place it at the end of code to create a partial-line comment as well.

### 2.4. Nested Expressions 
Data scientists and computer scientists love to nest expressions to save on space. 

*Note:* we are using some common, useful functions: `max`, `min`, `abs`

**Question 2.4.1** <br/>
Suppose we are interested in heights that are very unusual.  We'll say that a height is unusual to the extent that it's far away from the average human height.  [An estimate](http://doi.org/10.1210/jcem.86.9.7875) of the average adult human height (averaging, we hope, over all humans on Earth today) is 1.688 meters.

Say Aditya is 1.21 meters tall and Botan's height is 1.85 meters. Use Python to compute who has the most 'unusual' height of the two.

In [0]:
aditya_height_m = 1.21
botan_height_m = 1.85
average_adult_human_height_m = 1.688

# The biggest distance from the average human height, among the two heights:
biggest_distance_m = max(abs(aditya_height_m - average_adult_human_height_m), abs(botan_height_m - average_adult_human_height_m))

# Print out our results in a nice readable format:
print('The biggest distance from the average height among these two people is', biggest_distance_m, 'meters.')

The biggest distance from the average height among these two people is 0.478 meters.


### 2.5. String Methods
You'll also see how to invoke *methods*.  A method is very similar to a function; however a method is a member function of an object. We will use methods on string objects now and later, on NumPy Array objects and Pandas DataFrame objects. Calling a method looks a little different than a function because the method is tied to a particular object: you call the method by typing the object name + `.` + method name.

    <expression that evaluates to a string>.<method name>(<argument>, <argument>, ...)

The `replace` method is shown below. String methods can be called on raw strings or on string variables.

In [0]:
# Replace one letter
'Hello'.replace('H', 'C')

'Cello'

In [0]:
# Replace a sequence of letters, which appears twice
word = 'hitchhiker'
word.replace('hi', 'ma')

'matchmaker'

The result of the `replace` method is another string, so you can call `replace` repeatedly.

In [0]:
# Calling replace on the output of another call to replace
'train'.replace('t', 'ing').replace('in', 'de')

'degrade'

Other string methods do not take any arguments at all, because the original string is all that's needed to compute the result. In these cases, parentheses are still needed, but there's nothing in between the parentheses. Some methods that take no arguments include `lower`, `upper`, `capitalize`, `title`.

In [0]:
'idAhO sTatE unIveRSitY'.title()

'Idaho State University'

All these string methods are useful, but most programmers don't memorize their names or how to use them.  Instead, people usually just search the internet for documentation and examples. A complete [list of string methods](https://docs.python.org/3/library/stdtypes.html#string-methods) appears in the Python language documentation. [Stack Overflow](http://stackoverflow.com) has a huge database of answered questions that often demonstrate how to use these methods to achieve various ends.

### 2.6. Strings as function arguments
The function `len` takes a single string as its argument and returns the number of characters in the string: its **len**gth.  

Note that it doesn't count *words*. `len('one small step for man')` is 22, not 5.

We could use the string method `count` to count the number of spaces in a sentence. The number of spaces plus 1 should generally equal the number of words in a sentence.

*Note:* We will see later that `len` can be used on Arrays and DataFrames too.

**Question 2.6.1**<br/>
Find the number of words, using the string method `count`, in the following sentence:
>But when you have seen vicious mobs lynch your mothers and fathers at will and drown your sisters and brothers at whim; when you have seen hate-filled policemen curse, kick and even kill your black brothers and sisters; when you see the vast majority of your twenty million Negro brothers smothering in an airtight cage of poverty in the midst of an affluent society; when you suddenly find your tongue twisted and your speech stammering as you seek to explain to your six-year-old daughter why she can’t go to the public amusement park that has just been advertised on television, and see tears welling up in her eyes when she is told that Funtown is closed to colored children, and see ominous clouds of inferiority beginning to form in her little mental sky, and see her beginning to distort her personality by developing an unconscious bitterness toward white people; when you have to concoct an answer for a five-year-old son who is asking: “Daddy, why do white people treat colored people so mean?”; when you take a cross-country drive and find it necessary to sleep night after night in the uncomfortable corners of your automobile because no motel will accept you; when you are humiliated day in and day out by nagging signs reading “white” and “colored”; when your first name becomes “nigger,” your middle name becomes “boy” (however old you are) and your last name becomes “John,” and your wife and mother are never given the respected title “Mrs.”; when you are harried by day and haunted by night by the fact that you are a Negro, living constantly at tiptoe stance, never quite knowing what to expect next, and are plagued with inner fears and outer resentments; when you go forever fighting a degenerating sense of “nobodiness”– then you will understand why we find it difficult to wait.

-Martin Luther King, “A Letter from Birmingham Jail.”

*Note:* Hyphenated words (ie "six-year-old") count as one word, so you do not need to consider hyphens.

In [0]:
a_very_long_sentence = 'But when you have seen vicious mobs lynch your mothers and fathers at will and drown your sisters and brothers at whim; when you have seen hate-filled policemen curse, kick and even kill your black brothers and sisters; when you see the vast majority of your twenty million Negro brothers smothering in an airtight cage of poverty in the midst of an affluent society; when you suddenly find your tongue twisted and your speech stammering as you seek to explain to your six-year-old daughter why she can’t go to the public amusement park that has just been advertised on television, and see tears welling up in her eyes when she is told that Funtown is closed to colored children, and see ominous clouds of inferiority beginning to form in her little mental sky, and see her beginning to distort her personality by developing an unconscious bitterness toward white people; when you have to concoct an answer for a five-year-old son who is asking: “Daddy, why do white people treat colored people so mean?”; when you take a cross-country drive and find it necessary to sleep night after night in the uncomfortable corners of your automobile because no motel will accept you; when you are humiliated day in and day out by nagging signs reading “white” and “colored”; when your first name becomes “nigger,” your middle name becomes “boy” (however old you are) and your last name becomes “John,” and your wife and mother are never given the respected title “Mrs.”; when you are harried by day and haunted by night by the fact that you are a Negro, living constantly at tiptoe stance, never quite knowing what to expect next, and are plagued with inner fears and outer resentments; when you go forever fighting a degenerating sense of “nobodiness”– then you will understand why we find it difficult to wait.'
a_very_long_sentence.count(' ')

309

## 3. NumPy Arrays

Up to now, we haven't done much that you couldn't do yourself by hand, without going through the trouble of learning Python.  Computers are most useful when a small amount of code performs a lot of work by *performing the same action* to *many different things*.

For example, in the time it takes you to calculate the 18% tip on a restaurant bill, a laptop can calculate 18% tips for every restaurant bill paid by every human on Earth that day.  (That's if you're pretty fast at doing arithmetic in your head!)

**Arrays** are how we put many values in one place so that we can operate on them as a group. For example, if `billions_of_numbers` is an array of numbers, the expression

    .18 * billions_of_numbers

gives a new array of numbers that's the result of multiplying each number in `billions_of_numbers` by .18 (18%).  Arrays are not limited to numbers; we can also put all the words in a book into an array of strings.

### 3.1. Making arrays
You can type in the data that goes in an array yourself, but that's not typically how programs work. Normally, we create arrays by loading them from an external source, like a data file.

First, though, let's learn how to start from scratch. 

Arrays are provided by a package called [NumPy](http://www.numpy.org/) (pronounced "NUM-pie" or, if you prefer to pronounce things incorrectly, "NUM-pee").  The package is called `numpy`, but it's standard to rename it `np` for brevity.  You can do that with:

In [0]:
import numpy as np

Now, to create an array, call the method `array`. Notice both curved and square brackets are needed. This is because you pass the `array` method a list, which is denoted with `[]` brackets. Run this cell to see an example:

In [0]:
np.array([0.125, 4.75, -1.3])

array([ 0.125,  4.75 , -1.3  ])

To create a multi-dimensional array, pass lists within a list:

In [0]:
np.array([[0,1,2],[3,4,5],[6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Question 3.1.1.** <br/> Make an array containing the numbers 0, 1, -1, $\pi$, and $e$, in that order.  Name it `interesting_numbers`. <br/> 
*Hint:* $\pi$ and $e$ are available in the `math` library as `math.pi` and `math.e`

In [0]:
import math
interesting_numbers = ...
interesting_numbers

array([ 0.        ,  1.        , -1.        ,  3.14159265,  2.71828183])

** `np.arange`**<br/>
Very often in data science, we want to work with many numbers that are evenly spaced within some range.  NumPy provides a special function for this called `arange`.  `np.arange(start, stop, space)` produces an array with all the numbers starting at `start` and counting up by `space`, stopping **before** `stop` is reached.

For example, the value of `np.arange(1, 6, 2)` is an array with elements 1, 3, and 5 -- it starts at 1 and counts up by 2, then stops before 6.  In other words, it's equivalent to `np.array(1, 3, 5)`.

`np.arange(4, 9, 1)` is an array with elements 4, 5, 6, 7, and 8.  (It doesn't contain 9 because `np.arange` stops *before* the stop value is reached.)

**Question 3.1.2.** <br/>Import `numpy` as `np` and then use `np.arange` to create an array with the multiples of 99 from 0 up to (**and including**) 9999.  (So its elements are 0, 99, 198, 297, etc.)

In [0]:
import numpy as np
multiples_of_99 = ...
multiples_of_99

array([   0,   99,  198,  297,  396,  495,  594,  693,  792,  891,  990,
       1089, 1188, 1287, 1386, 1485, 1584, 1683, 1782, 1881, 1980, 2079,
       2178, 2277, 2376, 2475, 2574, 2673, 2772, 2871, 2970, 3069, 3168,
       3267, 3366, 3465, 3564, 3663, 3762, 3861, 3960, 4059, 4158, 4257,
       4356, 4455, 4554, 4653, 4752, 4851, 4950, 5049, 5148, 5247, 5346,
       5445, 5544, 5643, 5742, 5841, 5940, 6039, 6138, 6237, 6336, 6435,
       6534, 6633, 6732, 6831, 6930, 7029, 7128, 7227, 7326, 7425, 7524,
       7623, 7722, 7821, 7920, 8019, 8118, 8217, 8316, 8415, 8514, 8613,
       8712, 8811, 8910, 9009, 9108, 9207, 9306, 9405, 9504, 9603, 9702,
       9801, 9900, 9999])

**Question 3.1.3**<br/>
Suppose stock quotes are provided every 5 seconds during market hours (9:30am to 4:00pm Eastern). The first quote occurs the instant the market opens and the last quote occurs the instant the market closes. Using the `numpy` method `arange`, create an array that contains the time, in seconds from the opening bell, of each stock quote during the trading day. 

In [0]:
quote_times = ...
quote_times

array([    0,     5,    10, ..., 23390, 23395, 23400])

### 3.2. Array indexing and slicing
The NBA salaries for the 573 players in the 2017-18 season are in the file "NBA_season1718_salary.csv", which is loaded into the `salaries` array for you below.

In [0]:
# Don't worry too much about what goes on in this cell.
import numpy as np
import pandas as pd
salariesdf = pd.read_csv("NBA_season1718_salary.csv")
salaries = salariesdf['season17_18'].values
salaries

array([3.4682550e+07, 3.3285709e+07, 3.1269231e+07, 2.9727900e+07,
       2.9512900e+07, 2.8703704e+07, 2.8530608e+07, 2.8530608e+07,
       2.8299399e+07, 2.7739975e+07, 2.7734405e+07, 2.6243760e+07,
       2.6153057e+07, 2.5686667e+07, 2.5289390e+07, 2.5000000e+07,
       2.4773250e+07, 2.4599495e+07, 2.3962573e+07, 2.3775506e+07,
       2.3775506e+07, 2.3775506e+07, 2.3775506e+07, 2.3500000e+07,
       2.3112004e+07, 2.3112004e+07, 2.3000000e+07, 2.2642350e+07,
       2.2642350e+07, 2.2642350e+07, 2.2642350e+07, 2.2471910e+07,
       2.2471910e+07, 2.2434783e+07, 2.1974719e+07, 2.1461010e+07,
       2.1000000e+07, 2.0566802e+07, 2.0559599e+07, 2.0061729e+07,
       2.0000000e+07, 1.9578455e+07, 1.9508958e+07, 1.9332500e+07,
       1.9301070e+07, 1.9000000e+07, 1.8868625e+07, 1.8868625e+07,
       1.8063850e+07, 1.8063850e+07, 1.7884176e+07, 1.7884176e+07,
       1.7826150e+07, 1.7765000e+07, 1.7745894e+07, 1.7190000e+07,
       1.7131148e+07, 1.7000450e+07, 1.7000000e+07, 1.7000000e

Use `sort` to sort the array in ascending order.

In [0]:
salaries.sort()
salaries

array([1.7224000e+04, 2.2248000e+04, 2.5000000e+04, 2.5000000e+04,
       2.5000000e+04, 2.5000000e+04, 2.6773000e+04, 4.6080000e+04,
       4.6080000e+04, 4.6080000e+04, 4.6080000e+04, 4.6080000e+04,
       4.6080000e+04, 4.6080000e+04, 5.0000000e+04, 5.0000000e+04,
       5.0000000e+04, 5.0000000e+04, 5.0000000e+04, 5.0000000e+04,
       5.0000000e+04, 5.0000000e+04, 5.0000000e+04, 5.0000000e+04,
       5.0000000e+04, 5.0000000e+04, 5.0000000e+04, 5.0000000e+04,
       5.0000000e+04, 5.0000000e+04, 5.0000000e+04, 5.0000000e+04,
       5.0000000e+04, 5.0000000e+04, 5.0000000e+04, 5.0000000e+04,
       5.0000000e+04, 5.0000000e+04, 5.0000000e+04, 5.0000000e+04,
       5.3465000e+04, 7.4159000e+04, 7.4159000e+04, 7.4159000e+04,
       7.4159000e+04, 8.3129000e+04, 8.3129000e+04, 8.3129000e+04,
       8.7552000e+04, 9.2160000e+04, 9.2160000e+04, 9.2160000e+04,
       9.2160000e+04, 9.2160000e+04, 9.2160000e+04, 9.2160000e+04,
       9.2858000e+04, 1.0000000e+05, 1.0000000e+05, 1.0000000e

The first element in the array (the smallest when it is sorted) is `salaries[0]`. Note that in Python, arrays start counting with zero. The second element in the array is `salaries[1]` and the tenth element is `salaries[9]`.

In [0]:
salaries[0]

17224.0

The last element in the array is `salaries[572]`.

In [0]:
salaries[572]

34682550.0

We can also access the last element by using `salaries[-1]`. In Python you use a negative sign to indicate that you are counting backwards from the end of the array. So `salaries[-2]` would be the second-to-last element in the array.

In [0]:
salaries[-1]

34682550.0

If we try to access `salaries[573]` we get an error.

In [0]:
salaries[573]

IndexError: index 573 is out of bounds for axis 0 with size 573

To select the first ten elements we take a 'slice' of the array using `:`.

In [0]:
salaries[:10]

array([17224., 22248., 25000., 25000., 25000., 25000., 26773., 46080.,
       46080., 46080.])

We can also slice the last ten elements.

In [0]:
salaries[-10:]

array([27739975., 28299399., 28530608., 28530608., 28703704., 29512900.,
       29727900., 31269231., 33285709., 34682550.])

To slice the 10th thru the 20th elements (inclusive) we use:

In [0]:
salaries[9:20]

array([46080., 46080., 46080., 46080., 46080., 50000., 50000., 50000.,
       50000., 50000., 50000.])

Note that the slice begins at the left value and continues up to but NOT including the right value. So we get elements `salaries[9]` thru `salaries[19]`, or eleven elements.

If the array is not sorted it is still easy to find the max and min values are. <br/> Use `max` to find what the highest salary was.

In [0]:
salaries.max()
# Note there are two ways to do this: we can use the free function max() or the numpy method max(). 
# Below is what the free function way would look like:
# max(salaries)

34682550.0

Use `min` to find what the lowest salary was.

In [0]:
salaries.min()

17224.0

Numpy has some other useful methods. Use `sum` to find the total amount of money paid to NBA players as salary in the 2017-18 season.

In [0]:
salaries.sum()

3357175993.0

Use `mean` to find what the average salary was.

In [0]:
salaries.mean()

5858945.886561954

We can easily do arithmetic with arrays.

In [0]:
salaries_in_millions = salaries / 1000000
salaries_in_millions

array([1.7224000e-02, 2.2248000e-02, 2.5000000e-02, 2.5000000e-02,
       2.5000000e-02, 2.5000000e-02, 2.6773000e-02, 4.6080000e-02,
       4.6080000e-02, 4.6080000e-02, 4.6080000e-02, 4.6080000e-02,
       4.6080000e-02, 4.6080000e-02, 5.0000000e-02, 5.0000000e-02,
       5.0000000e-02, 5.0000000e-02, 5.0000000e-02, 5.0000000e-02,
       5.0000000e-02, 5.0000000e-02, 5.0000000e-02, 5.0000000e-02,
       5.0000000e-02, 5.0000000e-02, 5.0000000e-02, 5.0000000e-02,
       5.0000000e-02, 5.0000000e-02, 5.0000000e-02, 5.0000000e-02,
       5.0000000e-02, 5.0000000e-02, 5.0000000e-02, 5.0000000e-02,
       5.0000000e-02, 5.0000000e-02, 5.0000000e-02, 5.0000000e-02,
       5.3465000e-02, 7.4159000e-02, 7.4159000e-02, 7.4159000e-02,
       7.4159000e-02, 8.3129000e-02, 8.3129000e-02, 8.3129000e-02,
       8.7552000e-02, 9.2160000e-02, 9.2160000e-02, 9.2160000e-02,
       9.2160000e-02, 9.2160000e-02, 9.2160000e-02, 9.2160000e-02,
       9.2858000e-02, 1.0000000e-01, 1.0000000e-01, 1.0000000e

You can do the same with addition, subtraction, multiplication, and exponentiation (`**`). 